app:
  kafka:
    zookeeper:
      clusters:
        lolsearcher:
          controller:
            server: localhost:9092
          brokers:
            broker1:
              server: localhost:9092
  riot_games:
    token_key: ${api_key}